const codes = {
    'afghanistan':'af',
    'albania':'al',
    'algeria':'dz',
    'andorra':'ad',
    'anguilla':'ai',
    'antarctica':'aq',
    'argentina':'ar',
    'armenia':'am',
    'australia':'au',
    'austria':'at',
    'bangladesh':'bd',
    'belgium':'be',
    'bermuda':'bm',
    'bolivia':'bo',
    'brazil':'br',
    'bulgaria':'bg',
    'canada':'ca',
    'chile':'cl',
    'china':'cn',
    'colombia':'co',
    'cuba':'cu',
    'denmark':'dk',
    'equador':'ec',
    'egypt':'eg',
    'france':'fr',
    'germany':'de',
    'india':'in',
    'indonesia':'id',
    'italy':'it',
    'japan':'jp',
    'malaysia':'my',
    'mexico':'mx',
    'netherlands':'nl',
    'new zealand':'nz',
    'poland':'pl',
    'portugal':'pt',
    'romania':'ro',
    'russia':'ru',
    'saudi arabia':'sa',
    'singapore':'sg',
    'south africa':'za',
    'spain':'es',
    'switzerland':'ch',
    'sweden':'se',
    'united kingdom':'gb',
    'united states':'us',   
}
const category = ['business','entertainment','general','health','science','sports','technology']

export { category, codes }